const {chromium}=require(process.env.PLAYWRIGHT_PATH || 'playwright');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
(async()=>{
  const output=path.join(__dirname,'artifacts');fs.mkdirSync(output,{recursive:true});
  const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
  const context=await browser.newContext({viewport:{width:1440,height:1100},deviceScaleFactor:1,colorScheme:'light',locale:'en-US'});
  const page=await context.newPage();
  await page.addInitScript(()=>{localStorage.setItem('fluidly-language','en');localStorage.setItem('fluidly-theme','light');});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  await page.goto('http://127.0.0.1:8765/',{waitUntil:'networkidle'});
  await page.waitForTimeout(3500);
  assert.equal(await page.title(),'Fluidly — Find your flow.');
  assert.equal(await page.locator('#canvas-error').isVisible(),false,await page.locator('#error-message').textContent());
  assert.equal(await page.locator('[data-language="en"]').getAttribute('aria-pressed'),'true');
  await page.locator('#pause-button').click();
  const fluidBeforeTheme=await page.locator('#fluid-canvas').evaluate(canvas=>canvas.toDataURL());
  await page.locator('#theme-button').click();
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  assert.equal(await page.locator('#fluid-canvas').evaluate(canvas=>canvas.toDataURL()),fluidBeforeTheme);
  assert.match(await page.locator('#theme-button').getAttribute('aria-label'),/light mode/);
  await page.locator('[data-language="ru"]').click();
  assert.equal(await page.locator('html').getAttribute('lang'),'ru');
  assert.equal(await page.locator('.panel-heading h2').textContent(),'Ваш эксперимент');
  assert.equal(await page.locator('#pause-button').getAttribute('aria-label'),'Продолжить симуляцию');
  assert.match(await page.title(),/Найдите свой поток/);
  await page.locator('[data-language="kk"]').click();
  assert.equal(await page.locator('html').getAttribute('lang'),'kk');
  assert.equal(await page.locator('.panel-heading h2').textContent(),'Сіздің тәжірибеңіз');
  assert.equal(await page.locator('[data-preset="ocean"] [data-preset-name]').textContent(),'Терең мұхит');
  await page.screenshot({path:path.join(output,'dark-kk.png'),fullPage:true});
  assert.deepEqual(await page.evaluate(()=>[localStorage.getItem('fluidly-language'),localStorage.getItem('fluidly-theme')]),['kk','dark']);
  const persisted=await page.context().newPage();
  await persisted.goto('http://127.0.0.1:8765/',{waitUntil:'networkidle'});
  assert.equal(await persisted.locator('html').getAttribute('lang'),'kk');
  assert.equal(await persisted.locator('html').getAttribute('data-theme'),'dark');
  await persisted.close();
  await page.locator('[data-language="en"]').click();
  await page.locator('#theme-button').click();
  await page.locator('#pause-button').click();
  assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
  await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});
  const fps=await page.locator('#fps').textContent();
  const canvas=page.locator('#fluid-canvas');
  const bounds=await canvas.boundingBox();
  await page.mouse.move(bounds.x+bounds.width*.3,bounds.y+bounds.height*.5);
  await page.mouse.down();await page.mouse.move(bounds.x+bounds.width*.7,bounds.y+bounds.height*.35,{steps:18});await page.mouse.up();
  assert.match(await page.locator('#canvas-instruction').getAttribute('class'),/dismissed/);
  await page.locator('#swirl').fill('48');await page.locator('#swirl').dispatchEvent('input');
  assert.equal(await page.locator('#swirl-value').textContent(),'48');
  await page.locator('[data-palette="bloom"]').click();assert.equal(await page.locator('#palette-name').textContent(),'Bloom');
  await page.locator('[data-preset="ocean"]').click();
  assert.equal(await page.locator('#canvas-preset').textContent(),'03 / Deep ocean');
  assert.equal(await page.locator('#swirl').inputValue(),'16');
  await page.locator('#pause-button').click();assert.equal(await page.locator('#run-status').textContent(),'TAKING A BREATHER');
  await canvas.focus();await page.keyboard.press('Space');assert.equal(await page.locator('#run-status').textContent(),'LIVE SIMULATION');
  await page.locator('#burst-button').click();
  await page.locator('#quality').selectOption('low');await page.waitForTimeout(500);
  assert.equal(await page.locator('#canvas-error').isVisible(),false);
  await page.locator('#quality').selectOption('high');await page.waitForTimeout(500);
  assert.equal(await page.locator('#canvas-error').isVisible(),false);
  await page.locator('#quality').selectOption('medium');
  const downloadPromise=page.waitForEvent('download');await page.locator('#capture-button').click();
  const download=await downloadPromise;await download.saveAs(path.join(output,'capture.png'));
  assert.ok(fs.statSync(path.join(output,'capture.png')).size>5000);
  await page.locator('#about-button').click();assert.equal(await page.locator('#info-dialog').isVisible(),true);
  await page.keyboard.press('Escape');assert.equal(await page.locator('#info-dialog').isVisible(),false);
  await page.locator('#fullscreen-button').click();await page.waitForTimeout(300);
  assert.equal(await page.evaluate(()=>!!document.fullscreenElement),true);
  await page.evaluate(()=>document.exitFullscreen());
  await page.locator('[data-preset="aurora"]').click();
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(700);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});
  const reduced=await browser.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce'});
  await reduced.goto('http://127.0.0.1:8765/');await reduced.waitForTimeout(500);
  assert.match(await reduced.locator('#simulation').getAttribute('class'),/paused/);
  assert.equal(await reduced.locator('#autopilot').isChecked(),false);
  await reduced.setViewportSize({width:1120,height:800});await reduced.waitForTimeout(300);
  await reduced.setViewportSize({width:1120,height:1000});await reduced.waitForTimeout(300);
  const pausedImage=await reduced.locator('#fluid-canvas').screenshot();
  assert.ok(pausedImage.length>10000,'Paused resize should retain visible fluid');
  const recovery=await browser.newPage();
  await recovery.goto('http://127.0.0.1:8765/');await recovery.waitForTimeout(500);
  await recovery.evaluate(()=>{window.loss= document.getElementById('fluid-canvas').getContext('webgl2').getExtension('WEBGL_lose_context');window.loss.loseContext();});
  await recovery.locator('#canvas-error').waitFor({state:'visible'});
  await recovery.evaluate(()=>window.loss.restoreContext());
  await recovery.locator('#canvas-error').waitFor({state:'hidden'});
  assert.doesNotMatch(await recovery.locator('#simulation').getAttribute('class'),/paused/);
  // A separate page exercises the unsupported-device recovery state.
  const unsupported=await browser.newPage();
  await unsupported.addInitScript(()=>{HTMLCanvasElement.prototype.getContext=function(){return null;};});
  await unsupported.goto('http://127.0.0.1:8765/');
  await unsupported.locator('#canvas-error').waitFor({state:'visible'});
  assert.match(await unsupported.locator('#error-message').textContent(),/WebGL 2/);
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({result:'PASS',fps,checks:['PHP page load','light and dark theme','fluid palette isolation','English, Russian, and Kazakh','preference persistence','GPU shader compilation','pointer drawing','sliders','palettes','presets','pause and keyboard resume','burst','all render qualities','PNG export','dialog','fullscreen','mobile overflow','reduced motion','paused resize','context loss and recovery','unsupported-device message'],errors},null,2));
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
